name: MultiWorld
api: [1.0.0, 2.0.0, 3.0.0, 3.0.0-ALPHA5, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 4.0.0]
author: GamakCZ
main: MultiWorld\MultiWorld
version: 1.0.0
description: MultiWorld plugin with advanced features

commands:
  multiworld:
    description: MultiWorld Commands
    aliases: [wm, mw]

permissions:
  mw.cmd.create:
    description: Permission for /mw create
    default: op
  mw.cmd.setspawn:
    description: Permission for /mw setspawn
    default: op
  mw.cmd.setdefault:
    description: Permission for /mw setdefault
    default: op
  mw.cmd.sethub:
    description: Permission for /mw sethub
    default: op
  mw.cmd.list:
    description: Permission for /mw list
    default: op
  mw.cmd.tp:
    description: Permission for /mw tp
    default: op
  mw.cmd.help:
    description: Permission for /mw help
    default: op
  mw.cmd.genlist:
    description: Permission for /mw genlist
    default: op
  mw.cmd.load:
    description: Permission for /mw load
    default: op
  mw.cmd.unload:
    description: Permission for /mw unload
    default: op
  mw.cmd.delete:
    description: Permission for /mw delete
    default: op
  mw.cmd.info:
    description: Permission for /mw info
    default: op
  mw.cmd.rename:
    description: Permission for /mw rename
    default: op
  mw.cmd.setdim:
    description: Permission for /mw setdimension
    default: op
  mw.cmd.stc:
    description: Permission for /mw stc
    default: op
  mw.gm.creative:
    description: Permission for creative out of Creative Worlds
    default: op
